# Generated by Django 3.2.7 on 2022-01-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purewish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to=settings.AUTH_USER_MODEL),
        ),
    ]
